### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by anrom7** [maxymkryval/homeworks_cycle#1]
Запитання та зауваження написав Вашому колезі. Що будете обчислювати? Дані взяли, далі щось має відбуватися, а потім вже візуалізація?

Тема: ?

**Comment by maxymkryval** [comment]
Щодо даних все вірно, є як поденна так і загальна статистика всіх кейсів. Після її аналізу буде візуалізація та виснови з проаналізованого. 
Тема: дослідження динаміки поширення COVID-19

**Comment by anrom7** [comment]
Ви хочете повторити щось таке https://dou.ua/forums/topic/30150/

**Comment by maxymkryval** [comment]
Ну ця тема має більше пряму ціль у плані передбачення поведінки хвороби. Ми ж з напарником хочемо аналізувати існуючі дані поки без прогнозування хвороби, бо, на нашу думку, це трішки виходить за межі нашої компетенції. Ми хочемо проаналізувати коронавірус і ознайомити користувачів з його поширення і надати зручний доступ до даних різного виду та за різні часові проміжки.
