### ISSUE TITLE
ДЗ3,4,5

### ISSUE THREAD

**Issue by anrom7** [maxymkryval/homeworks_cycle#3]
Бачу тільки одного розробника.
Що за файл blabla?
Не знайшов де використовуються ADT.
ООП  ?

**Comment by maxymkryval** [comment]
Розробників двоє, а на гітхаб завантажував тільки я, комунікували через телеграм. 
Файл блабла був просто тестовий бо якийсь баг виникав при створенні і перевіряв ним. 
У нас реалізовано допоміжний клас HelpPromo, чия робота ґрунтується на Array ADT, оскільки  клас по суті слугує колекцією для інформації, отриманої в json-форматі, що і є основним прикладом використання адт.
Якщо ми з партнером не помиляємось, використання тільки ООП не було обов'язковою умовою.
